modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/minerguy341/thaumaturgy-the-new-age/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "minerguy341"
description = '''
${description}
'''

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
type = "required"
versionRange = "[13,)"
ordering = "AFTER"
side = "BOTH"
