minecraft_version=1.21.1
loader_version=0.16.14

# Fabric API
fabric_version=0.116.13+1.21.1
neoforge_version=21.1.235

# Architectury API (dev.architectury:architectury-{loader})
architectury_version=13.0.8
